### ISSUE TITLE
No reset timer when write a file multiple times

### ISSUE THREAD

**Issue by cobolbaby** [Q1-Energie-AG/fswatch#1]

**Comment by moogle19** [comment]
Time should now be resetted correctly.

**Comment by cobolbaby** [comment]
Sorry, I still did not find the relevant logic. Can you quote the code?

**Comment by moogle19** [comment]
This continue resets the timer if an event other than rename or delete is received:

https://github.com/Q1-Energie-AG/fswatch/blob/fd82a596979de92ddf9dad573d126afe00a1022a/watcher.go#L175
